name: Auto-merge Dependabot PRs

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened, labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add existing labels only
        uses: actions/github-script@v7
        with:
          script: |
            const wanted = ['dependencies'];
            const { data: repoLabels } = await github.rest.issues.listLabelsForRepo({ owner: context.repo.owner, repo: context.repo.repo, per_page: 100 });
            const existing = new Set(repoLabels.map(l => l.name.toLowerCase()));
            const toAdd = wanted.filter(n => existing.has(n));
            if (toAdd.length) {
              await github.rest.issues.addLabels({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.payload.pull_request.number, labels: toAdd });
            } else {
              core.info('No matching existing labels to add');
            }

      - name: Enable auto-merge (squash) for non-major updates
        if: steps.meta.outputs.update-type != 'version-update:semver-major'
        uses: actions/github-script@v7
        with:
          script: |
            const pull_number = context.payload.pull_request.number;
            const { data: pr } = await github.rest.pulls.get({ owner: context.repo.owner, repo: context.repo.repo, pull_number });
            await github.graphql(`
              mutation($pullRequestId: ID!) {
                enablePullRequestAutoMerge(input: {pullRequestId: $pullRequestId, mergeMethod: SQUASH}) { clientMutationId }
              }
            `, { pullRequestId: pr.node_id });

