name: Generate Release Notes

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Release Notes via API (linux)
        env:
          API_KEY: ${{ secrets.RELEASE_NOTES_API_KEY }}
          BASE_URL: https://gpt.lazarev.cloud/ollama/v1
        run: |
          bash scripts/generate_release_notes.sh > RELEASE_NOTES.md
      - name: Update Release body
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('RELEASE_NOTES.md', 'utf8');
            await github.rest.repos.updateRelease({ owner: context.repo.owner, repo: context.repo.repo, release_id: context.payload.release.id, body });

