name: Generate Release Notes

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Release Notes
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const tag = context.payload.release.tag_name;
            const { data: commits } = await github.rest.repos.listCommits({ owner, repo, per_page: 100 });
            const notes = commits.map(c => `- ${c.commit.message}`).join('\n');
            await github.rest.repos.updateRelease({ owner, repo, release_id: context.payload.release.id, body: notes });

