name: Security checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'

jobs:
  pip-audit:
    name: Python dependency audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pip-audit
      - name: Run pip-audit
        run: |
          pip-audit -r requirements.txt --strict

  trivy-image:
    name: Trivy scan (image)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: lcm:ci-scan
          build-args: |
            TORCH_INDEX_URL=https://download.pytorch.org/whl/cpu
      - name: Trivy scan image
        uses: aquasecurity/trivy-action@9ab158e8597f3b310480b9a69402b419bc03dbd5 # 0.22.0
        with:
          image-ref: lcm:ci-scan
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@b611370bb5703a7efb587f9d136a52ea24c5c38a # v3
        with:
          sarif_file: trivy-results.sarif

